### ISSUE TITLE
Windows 10 notify error

### ISSUE THREAD

**Issue by KoderKaul** [niharbansal02/cowin_automation#4]
I am getting the following error for Windows 10. I configured the files as mentioned in the readme.
```
Traceback (most recent call last):
  File "script.py", line 112, in <module>
    obj.work()
  File "script.py", line 83, in work
    notifObj.notify(notifStr, name)
  File "C:\Users\Lenovo\Desktop\cowin_automation-master\helper\notifier.py", line 30, in notify
    self.win_notify(head, msg)
  File "C:\Users\Lenovo\Desktop\cowin_automation-master\helper\notifier.py", line 33, in win_notify
    toast = ToastNotifier()
NameError: name 'ToastNotifier' is not defined
```

**Comment by niharbansal02** [comment]
Hi @KoderKaul , please make sure you have all the dependencies installed. You can refer to the README for help with installation.
